FROM node:20-alpine

RUN apk add --no-cache curl unzip \
  && curl -fsSL https://bun.sh/install | bash \
  && ln -s /root/.bun/bin/bun /usr/local/bin/bun


ENV NODE_ENV=production

WORKDIR /app

# Copy only the necessary files for migrations
COPY package.json bun.lockb ./
COPY drizzle.config.ts ./
COPY src/db ./src/db
COPY drizzle ./drizzle

RUN bun install

CMD ["npx", "drizzle-kit", "migrate"] 
