services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:postgres@db:5432/postgres}
      - DATABASE_URL_EXTERNAL=${DATABASE_URL_EXTERNAL:-postgres://postgres:postgres@localhost:5432/postgres}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    name: my_network
    driver: bridge
