FROM node:20

RUN curl -fsSL https://bun.sh/install | bash

ENV PATH="/root/.bun/bin:$PATH"
ENV NODE_ENV=production

WORKDIR /app

# Copy only the necessary files for migrations
COPY drizzle ./drizzle
COPY drizzle.config.ts package.json bun.lockb tsconfig.json ./
COPY src/db ./src/db
COPY src/env.ts ./src/env.ts

RUN bun install

CMD ["bun", "src/db/migrate.ts"]
