services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      APP_URL: ${APP_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      DATABASE_URL_EXTERNAL: ${DATABASE_URL_EXTERNAL}
      DATABASE_URL: ${DATABASE_URL}
      RESEND_KEY: ${RESEND_KEY}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    healthcheck:
      test: CMD-SHELL pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  my_network:
    name: my_network
    driver: bridge
