FROM node:20

RUN curl -fsSL https://bun.sh/install | bash

ENV PATH="/root/.bun/bin:$PATH"
ENV NODE_ENV=production

WORKDIR /app

COPY package.json bun.lockb ./
COPY src/db ./src/db
COPY src/env.ts ./src/env.ts
COPY scripts/cron ./scripts/cron

RUN bun install

RUN apt-get update && apt-get -y install cron

COPY crontab /etc/cron.d/app-cron
RUN chmod 0644 /etc/cron.d/app-cron
RUN crontab /etc/cron.d/app-cron

RUN touch /var/log/cron.log

CMD cron && tail -f /var/log/cron.log 
